spring.application.name=demo

#DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/EZEKIEL
spring.datasource.username=postgres
spring.datasource.password=Ezekiel@1
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
